export async function get() {
	return {
		body: `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
    <url>
        <loc>https://analistul.com/</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/institutii</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/cadre-didactice</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/blog</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/login</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/gradinite</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/scoli</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/colegii</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/licee</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/postliceale</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/universitati</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/academii</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/invatatori</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/educatori</loc>
        <changefreq>weekly</changefreq>
    </url>
    <url>
        <loc>https://analistul.com/profesori</loc>
        <changefreq>weekly</changefreq>
    </url>
</urlset>`
	};
}
